"""Record complete installed MonsterOld; preserve prior QA and unrelated tracking."""
import csv,io,json,sys
from pathlib import Path
ROOT=Path(__file__).resolve().parents[3];HERE=Path(__file__).resolve().parent
sys.path.insert(0,str(ROOT/'pipeline/scripts'))
from palette_work_plan import file_sha,write_json
from workspace_paths import get_path
load=lambda p:json.loads(p.read_text(encoding='utf-8-sig'))
gen=load(HERE/'current-generation.json');prod=load(HERE/'production.json');verification=load(HERE/'verification.json');receipt=load(HERE/'ingame-installation/active-test.json');baseline=load(HERE/'baseline.json')
prod['stats']={**prod['stats'],**prod.get('cumulative_stats',{})}
assert receipt['status']=='installed-pending-ingame-qa'
game=get_path('bg2ee_game_root',required=True)
assert file_sha(game/'iee-assets/creature-sprites/CreatureSprites-XN.catalog')==gen['catalog']['sha256']
for r in baseline['preserved']:assert file_sha(game/r['relative_path']).lower()==r['sha256'].lower()
for s in receipt['new_shards']:assert file_sha(game/s['registry']).upper()==s['sha256']
for f in receipt['fixtures']:assert file_sha(game/f['target'])==f['sha256']
write_json(HERE/'installed-native-verification.json',dict(passed=True,catalog_sha256=gen['catalog']['sha256'],dll_sha256=gen['dll']['sha256'],DLL_unchanged=True,preserved_files=len(baseline['preserved']),resources=217,frames=17752,logical_resource_bindings=218,bound_frames=17754,fixtures=46,native_world=verification['native_world']['combined'],ingame_QA=False,release=False))
reference='docs/measurements/'+HERE.name+'/current-generation.json';snapshot='docs/measurements/'+HERE.name+'/installation-verification.json';receiptref='docs/measurements/'+HERE.name+'/ingame-installation/active-test.json'
p=ROOT/'sprite/index/q3m-work-tracking.json';track=load(p);family=next(f for f in track['families'] if f['engine_section']=='monster_old');totals=track['queue_totals']
assert totals['current_recipe_complete_families']==10 and totals['current_recipe_installed_animation_ids']==80 and totals['current_recipe_ingame_accepted_animation_ids']==79
family['current_colour_witness'].update(state='installed-via-complete-native-palette-family-ingame-pending',installation_reference=snapshot)
family['source_dedup']['remaining_gpu_work']=0
family['current_full_production']=dict(reference=reference,selection='docs/measurements/'+HERE.name+'/selection.json',animation_ids=gen['animation_ids'],source_absent_animation_ids=prod['plan']['source_absent_animation_ids'],models=18,colour_variants=46,physical_resources=217,physical_frames=17752,logical_resource_bindings=218,bound_frames=17754,unique_native_BAM=79,original_native_frames=6917,unique_source_work=prod['plan']['unique_source_work'],unique_encoded_work=prod['plan']['unique_encoded_work'],stats=prod['stats'],resume_cache_hits=verification['resume']['encoded_cache_hits'],runtime_reference=gen['runtime']['path'],installation_reference=receiptref,installation_snapshot=snapshot,state='family-complete-available-produced-installed-ingame-QA-pending',registry_version=7,SDF=False,qa_ingame=False,release=False)
family['state']=family['current_full_production']['state'];family['current_installation']=dict(state='installed-ingame-pending',reference=snapshot,receipt=receiptref,catalogue_sha256=gen['catalog']['sha256'],dll_sha256=gen['dll']['sha256'],animation_ids=gen['animation_ids'],SDF=False,qa_ingame=False)
assert not any(e['family']=='monster_old' for e in track['current_recipe_complete_productions'])
track['current_recipe_complete_productions'].append(dict(family='monster_old',**family['current_full_production']))
totals.update(current_recipe_complete_families=11,current_recipe_complete_animation_ids=126,current_recipe_installed_animation_ids=126)
assert totals['current_recipe_ingame_accepted_families']==9 and totals['current_recipe_ingame_accepted_animation_ids']==79
track['engine_integration'].update(installed_candidate_reference=reference,latest_installation_verification_reference=snapshot)
track['colour_variants']['state']+='-Monster_old-V7-no-SDF-installed-ingame-pending';track['recorded_on']='2026-10-05';write_json(p,track)
p=ROOT/'sprite/index/q3m-work-items.csv';raw=p.read_bytes();lines=raw.decode('utf-8-sig').splitlines(keepends=True);fields=next(csv.reader([lines[0]]));out=[lines[0]];byid={w['animation_id']:w for w in prod['plan']['witnesses']};changed=[]
for line in lines[1:]:
    row=dict(zip(fields,next(csv.reader([line]))))
    if row['animation_id'] not in byid:out.append(line);continue
    row.update(queue_state='q3m-v7-full-produced-installed-ingame-pending',colour_variant_state='v7-full-native-palettes-no-SDF-x2-installed-ingame-pending',q3m_v7_full_production_reference=reference,q3m_v7_installation_reference=receiptref,q3m_final_work_count_known=str(byid[row['animation_id']]['encoded_work']))
    text=io.StringIO(newline='');csv.DictWriter(text,fields,lineterminator='\r\n' if line.endswith('\r\n') else '\n').writerow(row);out.append(text.getvalue());changed.append(row['animation_id'])
assert len(changed)==46;p.write_bytes((b'\xef\xbb\xbf' if raw.startswith(b'\xef\xbb\xbf') else b'')+''.join(out).encode('utf-8'))
p=ROOT/'sprite/SUIVI_Q3M.md';t=p.read_text(encoding='utf-8');t=t.replace('80 IDs /10 familles disponibles complètes installées','126 IDs /11 familles disponibles complètes installées')
t=t.replace('| `monster_old` | 46/54 | — | Anciennes animations BG1, séquences/directions et palettes propres ; ours, loups, basilics, demi-ogres. |','| `monster_old` | 46/54 | — | **Famille disponible complète installée, QA en attente**, Q3m V7 K6 x2 amélioré sans SDF ;18 modèles/46 variantes natives,79 BAM/217 feuilles/17 752 frames physiques (218 liaisons/17 754 frames liées). Huit IDs sans source. |')
t+='\n## Monster_old : complet disponible installé — 2026-10-05\n\n- 46 IDs/18 modèles,79 BAM natifs/6 917 frames originales ;217 feuilles/17 752 frames physiques (218 liaisons/17 754 frames liées) Q3m V7 K6 x2 palette améliorée sans SDF. 16 785 encodages uniques ;'+str(prod['stats'].get('new_neural_targets',0))+' cibles neuves, aucune répétition physique retraitée. Trente palettes BMP natives authentifiées, sept INV auxiliaires conservés.\n- Huit IDs7D01–7D08 sans BAM exclus. DLL/INI/shaders/acquis conservés ;46 CRE tests QOLD neutres sans scripts/effets/équipement. [Run/CLUA](../docs/measurements/'+HERE.name+'/README.md).\n- Onze familles/126 IDs installés ;neuf familles/79 IDs acceptés inchangés. **QA ingame en attente**, aucune release/validation déduite.\n';p.write_text(t,encoding='utf-8')
p=ROOT/'sprite/index/README.md';t=p.read_text(encoding='utf-8');t+='\n- Monster_old **complet disponible installé, QA en attente** : [run](../../docs/measurements/'+HERE.name+'/README.md), [46 CLUA neutres](../../docs/measurements/'+HERE.name+'/CLUA.txt). 18 modèles/46 palettes natives,79 BAM/217 feuilles/17 752 frames physiques (218 liaisons/17 754 frames liées) Q3m V7 K6 x2 amélioré sans SDF ;huit IDs7D01–7D08 absents. Onze familles/126 IDs installés ;neuf familles/79 IDs acceptés conservés.\n';p.write_text(t,encoding='utf-8')
(HERE/'README.md').write_text('# Monster_old complet disponible — Q3m amélioré x2 installé\n\n- **Installé, QA ingame en attente** ;46 IDs/18 modèles distincts, trente palettes de remplacement authentifiées ;Q3m V7 K6 x2 palette améliorée/CatmullRom sans SDF.\n- Toutes actions/directions G1/G2/G1E/G2E, sept INV auxiliaires ;79 BAM/6 917 frames originales,217 feuilles/17 752 frames physiques (218 liaisons/17 754 frames liées). Huit IDs7D01–7D08 sans source exclus.\n- 16 785 travaux compatibles uniques ;statistiques exactes `production.json` ;'+str(prod['stats'].get('new_neural_targets',0))+' nouvelles cibles K6, reprise16 785 hits sans import Torch ;aucun groupe spatial/tuiles dans ce profil.\n- Géométrie/cycles/profils/indices spéciaux/représentants vérifiés sur17 754 frames ;décodeur natif K6×3formats isolé/combiné. Anciennes161 animations/6 885 composants/55 515 routes préservées ;actif207 IDs/7 102 ressources/1 723 427 frames/55 733 routes.\n- DLL/INI/trois shaders acquis inchangés ;'+str(len(baseline['preserved']))+' fichiers acquis SHA préservés.46 CRE tests QOLD neutres sans scripts/effets/équipement ;`CLUA.txt`, `creatures.json`, `comparison.png`.\n- Autorités : `current-generation.json`, `production.json`, `verification.json`, `catalog-proof.json`, `ingame-installation/active-test.json`, `installation-verification.json`, `installed-native-verification.json`. Sauvegarde catalogue `work/before`, restauration `restore.ps1` jeu/InfinityLoader fermés.\n- Onze familles/126 IDs installés ;neuf familles/79 IDs acceptés inchangés. Aucun état QA/release déduit.\n',encoding='utf-8')
print(json.dumps(dict(installed=True,family='monster_old',animation_ids=46,resources=217,frames=17752,DLL_unchanged=True,accepted_ids=79)))
