"""Installed pending QA; update only scoped queue and references, no release."""
import csv,io,json,subprocess,sys
from pathlib import Path
ROOT=Path(__file__).resolve().parents[3];HERE=Path(__file__).resolve().parent
sys.path.insert(0,str(ROOT/'pipeline/scripts'))
from palette_work_plan import file_sha,write_json
from workspace_paths import get_path
load=lambda p:json.loads(p.read_text(encoding='utf-8-sig'))
gen=load(HERE/'current-generation.json');prod=load(HERE/'production.json');verification=load(HERE/'verification.json');receipt=load(HERE/'ingame-installation/active-test.json');baseline=load(HERE/'baseline.json')
assert receipt['status']=='installed-pending-ingame-qa'
game=get_path('bg2ee_game_root',required=True)
assert file_sha(game/'iee-assets/creature-sprites/CreatureSprites-XN.catalog')==gen['catalog']['sha256'] and file_sha(game/'InfinityEngine-Enhancer.dll')==gen['dll']['sha256']
for r in baseline['preserved']:assert file_sha(game/r['relative_path']).lower()==r['sha256'].lower()
for s in receipt['new_shards']:assert file_sha(game/s['registry']).upper()==s['sha256']
for f in receipt['fixtures']:assert file_sha(game/f['target'])==f['sha256']
p=subprocess.run([str(HERE/'composite_probe.exe'),str(game/'iee-assets/creature-sprites'),str(HERE/'work/composite.oracle')],capture_output=True,text=True,encoding='utf-8');(HERE/'native-installed.log').write_text(p.stdout+p.stderr,encoding='utf-8');assert p.returncode==0,(p.stdout[-1000:],p.stderr)
native=json.loads(next(s for s in reversed(p.stdout.splitlines()) if s.startswith('{')));assert native==verification['native_composite']
write_json(HERE/'installed-native-verification.json',dict(passed=True,native_composite=native,catalog_sha256=gen['catalog']['sha256'],dll_sha256=gen['dll']['sha256'],preserved_files=len(baseline['preserved']),new_shards=132,fixtures=7,ingame_QA=False,release=False))
reference='docs/measurements/'+HERE.name+'/current-generation.json';snapshot='docs/measurements/'+HERE.name+'/installation-verification.json';receiptref='docs/measurements/'+HERE.name+'/ingame-installation/active-test.json'
p=ROOT/'sprite/index/q3m-work-tracking.json';track=load(p);totals=track['queue_totals'];assert totals['current_recipe_complete_families']==9 and totals['current_recipe_complete_animation_ids']==73 and totals['current_recipe_ingame_accepted_animation_ids']==72
totals.update(current_recipe_complete_families=10,current_recipe_complete_animation_ids=80,current_recipe_installed_animation_ids=80)
family=next(f for f in track['families'] if f['engine_section']=='monster_quadrant');family['source_dedup']['remaining_gpu_work']=0
family['current_full_production']=dict(reference=reference,selection='docs/measurements/'+HERE.name+'/selection.json',animation_ids=gen['animation_ids'],source_absent_animation_ids=['0x1101','0x1105'],models=2,colour_variants=7,physical_resources=132,unique_native_BAM=36,physical_frames=12928,original_native_frames=3552,unique_source_work=prod['plan']['unique_source_work'],unique_encoded_work=12476,encoded_cache_hits=prod['stats']['encoded_cache_hits'],new_encoded_work=prod['stats']['new_encoded_work'],special_work=prod['stats']['special_work'],new_neural_targets=prod['stats']['new_neural_targets'],resume_cache_hits=12476,scope='complete native four-quadrant G1/G2/G3, native E directions, all geometry/cycles including 65 zero-area variant declarations',runtime_reference=gen['runtime']['path'],installation_reference=receiptref,installation_snapshot=snapshot,state='family-complete-available-produced-installed-ingame-QA-pending',registry_version=7,SDF=False,qa_ingame=False,release=False)
family['state']=family['current_full_production']['state'];family['current_installation']=dict(state='installed-ingame-pending',reference=snapshot,receipt=receiptref,catalogue_sha256=gen['catalog']['sha256'],dll_sha256=gen['dll']['sha256'],animation_ids=gen['animation_ids'],SDF=False,qa_ingame=False)
family['current_colour_witness'].update(state='installed-via-complete-family-ingame-pending',installation_reference=snapshot)
assert not any(e['family']=='monster_quadrant' for e in track['current_recipe_complete_productions']);track['current_recipe_complete_productions'].append(dict(family='monster_quadrant',**family['current_full_production']))
track['engine_integration'].update(installed_candidate_reference=reference,latest_installation_verification_reference=snapshot);track['colour_variants']['state']+='-Monster_quadrant-V7-no-SDF-installed-ingame-pending';write_json(p,track)
p=ROOT/'sprite/index/q3m-work-items.csv';raw=p.read_bytes();lines=raw.decode('utf-8-sig').splitlines(keepends=True);fields=next(csv.reader([lines[0]]));out=[lines[0]];byid={w['animation_id']:w for w in prod['plan']['witnesses']};changed=[]
for line in lines[1:]:
    row=dict(zip(fields,next(csv.reader([line]))))
    if row['animation_id'] not in byid:out.append(line);continue
    row.update(queue_state='q3m-v7-full-produced-installed-ingame-pending',colour_variant_state='v7-full-native-quadrant-no-SDF-x2-installed-ingame-pending',q3m_v7_full_production_reference=reference,q3m_v7_installation_reference=receiptref,q3m_final_work_count_known=str(byid[row['animation_id']]['encoded_work']))
    s=io.StringIO(newline='');writer=csv.DictWriter(s,fields,lineterminator='\r\n' if line.endswith('\r\n') else '\n');writer.writerow(row);out.append(s.getvalue());changed.append(row['animation_id'])
assert len(changed)==7;p.write_bytes((b'\xef\xbb\xbf' if raw.startswith(b'\xef\xbb\xbf') else b'')+''.join(out).encode('utf-8'))
p=ROOT/'sprite/SUIVI_Q3M.md';t=p.read_text(encoding='utf-8');t=t.replace('| `monster_quadrant` | 7/9 | — | Assemblage de plusieurs quadrants ; centres et ordre de dessin conservés. Grandes wyvernes, tanar\'ri. |','| `monster_quadrant` | 7/9 | — | **Famille disponible complète Q3m V7 x2 palette améliorée sans SDF installée, QA en attente** ; deux modèles/sept palettes, 36 BAM natifs/132 feuilles/12 928 frames ; quadrants vides préservés, MWDR1101/1105 sans source. |')
t=t.replace('73 IDs /9 familles disponibles complètes installées','80 IDs /10 familles disponibles complètes installées')
t+='\n## Monster_quadrant : famille complète disponible installée — 2026-10-04\n\n- Demande utilisateur : lot complet Q3m amélioré +installation. **Sept IDs/deux modèles/sept palettes**, 36 BAM natifs/3 552 frames source ;132 feuilles variantes/12 928 frames. Q3m V7 K6 x2/CatmullRom sans SDF ;33 BAM hors appels natifs exclus ;1101/1105 MWDR sans source.\n- Travail :12 476 identités ;200 hits acquis SHA inchangés +'+str(prod['stats']['new_encoded_work'])+' nouveaux encodages +'+str(prod['stats']['special_work'])+' spéciaux ;'+str(prod['stats']['new_neural_targets'])+' nouvelles cibles K6. Reprise12 476 hits sans Torch.\n- **65 déclarations0×0 natives (21 physiques) conservées**, plans vides, centres/cycles/représentants exacts ; lecteur V7 limité à quatre resrefs fixes, native per-cell owner4 saute leurs dessins sans pixels inventés. DLL basée exactement sur le parent Layered accepté ; V10 Character en stock non activé, shaders/INI inchangés.\n- '+str(native['native_composites'])+' assemblages offline quatre parties/'+str(verification['assembly_cases_with_empty_parts'])+' cas avec quadrants vides, tous12928frames K6×3formats isolé/combiné, Ankheg V9 hérité. Catalogue parent154IDs/6753ressources/55383routes préservé ; actif161IDs/6885ressources/55515routes.\n- [Run/CLUA](../docs/measurements/'+HERE.name+'/README.md) ;132 feuilles +DLL +catalogue +sept CRE neutres sans effets/inventaire/scripts. SHA'+str(len(baseline['preserved']))+' fichiers acquis conservés. **Dix familles/80 IDs installés ; huit familles/72 IDs acceptés inchangés**, QA ingame en attente ; aucune release.\n';p.write_text(t,encoding='utf-8')
p=ROOT/'sprite/index/README.md';t=p.read_text(encoding='utf-8');t+='\n- Monster_quadrant complet disponible **produit/installé, QA ingame en attente** : [run/sept CLUA](../../docs/measurements/'+HERE.name+'/README.md), deux modèles/sept palettes natives, 36 BAM/132 feuilles/12 928 frames Q3m V7 x2 amélioré sans SDF. MWDR1101/1105 absents ;65 déclarations0×0 préservées. Dix familles/80 IDs installés ; huit familles/72 IDs acceptés.\n';p.write_text(t,encoding='utf-8')
(HERE/'README.md').write_text('# Monster_quadrant complet — Q3m x2 palette améliorée, sans SDF\n\n- **Produit/installé, QA ingame en attente**. Sept IDs1000/1003/1004/1100/1102/1103/1104 ;deux modèles/sept palettes BMP natives.\n- 36 BAM monde natifs/3 552 frames ;132 feuilles variantes/12 928 frames. 12 476 encodages uniques,200 hits acquis, '+str(prod['stats']['new_encoded_work'])+' nouveaux encodages +'+str(prod['stats']['special_work'])+' spéciaux ;'+str(prod['stats']['new_neural_targets'])+' nouvelles cibles ;reprise12 476 hits sans Torch.\n- 33 ressources de préfixe hors constructeur exclues, natives Large16/ancien MTAN conservées ;MWDR1101/1105 sans source.65 déclarations0×0 variantes exactes :aucun pixel inventé, centres/cycles/représentants inchangés.\n- Native owner4/render3305A0 per-cell, quatre quadrants ;lecteur V7 nativeKind0 seulement accepte les quatre resrefs vides connus et ignore leurs dessins. Contrat palette source/partenaires natif conservé ;runtime parent Layered accepté +delta vide, V10 Character stock non activé, shaders/INI inchangés.\n- Vérifications :toutes frames/slots, K6×trois formats isolé/combiné ;'+str(native['native_composites'])+' assemblages offline/'+str(verification['assembly_cases_with_empty_parts'])+' cas partiellement vides ;65 quadrants vides metadata ;Ankheg V9. Parent154IDs/6753composants/55383routes inchangés ;'+str(len(baseline['preserved']))+' fichiers acquis SHA conservés.\n- Installation132 feuilles +catalogue +DLL +septCRE tests neutres, sources BAM/BMP/INI/CRE stock inchangées. `CLUA.txt`, `creatures.json` ;sauvegarde `work/before`, restauration `restore.ps1`. Catalogue '+gen['catalog']['sha256']+' ; DLL '+gen['dll']['sha256']+'.\n- Autorités : `current-generation.json`, `production.json`, `verification.json`, `runtime.json`, `ingame-installation/active-test.json`, `installation-verification.json`, `installed-native-verification.json`. Catalogue actif161IDs/6885ressources/1 705 675frames/55515routes. Dix familles/80 IDs installés ;huit familles/72 IDs acceptés inchangés. Pas de QA/release/commit déduit.\n',encoding='utf-8')
print(json.dumps(dict(installed=True,changed_CSV_ids=changed,accepted_families=8,accepted_ids=72,complete_families=10,complete_ids=80,preserved=len(baseline['preserved']))),flush=True)
