"""Generate/check native tables from the immutable phase-1 palette contract."""
from __future__ import annotations
import argparse
import hashlib
from pathlib import Path

from palette_monster_contract import documents, ROOT

OUTPUT = ROOT / "engine/InfinityEngine-Enhancer/source-patchee/src/iee/core/monster_palette_profiles.h"


def render():
    c, profiles = documents()
    lines = ['#pragma once', '// Generated by pipeline/scripts/generate_monster_palette_profiles.py; do not edit.',
             '#include <array>', '#include <cstddef>', '#include <cstdint>', '#include <span>', '#include <string_view>',
             'namespace iee::core::palette_fraction {',
             f'inline constexpr std::string_view kMonsterProfilesSha256 = "{c["profiles_file_sha256"]}";',
             'inline constexpr std::uint32_t kMonsterRule = 2;',
             'inline constexpr std::array<std::array<std::uint8_t,256>,6> kMonsterSuccessors{{']
    for p in profiles.values():
        values = list(bytes.fromhex(p['successor_u8_hex']))
        lines.append('  std::array<std::uint8_t,256>{{' + ','.join(map(str, values)) + '}},')
    lines += ['}};', 'inline constexpr std::array<std::array<std::uint32_t,256>,6> kMonsterSourceRgb{{']
    for p in profiles.values():
        raw = bytes.fromhex(p['base_bgra_hex'])
        values = [int.from_bytes(raw[i:i+3], 'little') for i in range(0,1024,4)]
        lines.append('  std::array<std::uint32_t,256>{{' + ','.join(f'0x{x:06x}u' for x in values) + '}},')
    lines += ['}};', 'struct MonsterSource { std::string_view ref; std::uint32_t profile; std::uint16_t animation; std::array<std::uint8_t,32> sha; };',
              'inline constexpr std::array<MonsterSource,39> kMonsterSources{{']
    for r in c['resources']:
        values = bytes.fromhex(r['canonical_sha256_registered'])
        lines.append('  MonsterSource{"' + r['resref'] + '",' + str(r['palette_profile_id']) + ',' + r['animation_id'].lower()
                     + ',{{' + ','.join(map(str,values)) + '}}},')
    lines += ['}};',
              'constexpr bool monster_profile(std::uint32_t p, std::uint32_t r) noexcept { return p >= 2 && p <= 7 && r == kMonsterRule; }',
              'inline bool monster_resource(std::uint32_t p, std::string_view ref, std::span<const std::byte> sha) noexcept {',
              '  for (const auto& source : kMonsterSources) if (source.profile == p && source.ref == ref) {',
              '    if (sha.size() != 32) return false;',
              '    for (std::size_t i=0;i<32;++i) if (std::to_integer<std::uint8_t>(sha[i]) != source.sha[i]) return false;',
              '    return true;', '  }', '  return false;', '}',
              'constexpr bool monster_owner(std::uint32_t p, std::uint32_t owner, std::uint16_t animation) noexcept {',
              '  if (owner != 3 || p < 2 || p > 7) return false;',
              '  return animation == (p < 4 ? 0x7f02 : p < 6 ? 0x7f30 : 0x7f07);', '}',
              'inline bool monster_source_palette(std::uint32_t p, std::uint16_t kind, std::span<const std::uint32_t> colors) noexcept {',
              '  if (p < 2 || p > 7 || kind != 0 || colors.size() != 256) return false;',
              '  for (std::size_t i=0;i<256;++i) {',
              '    const auto a=colors[i] >> 24;',
              '    if ((colors[i] & 0xffffffu) != kMonsterSourceRgb[p-2][i] || (a != 0 && a != 255)) return false;',
              '  }', '  return true;', '}', '}  // namespace iee::core::palette_fraction', '']
    return '\n'.join(lines)


if __name__ == '__main__':
    parser=argparse.ArgumentParser();parser.add_argument('--check',action='store_true');args=parser.parse_args()
    data=render().encode()
    if args.check:
        assert OUTPUT.read_bytes()==data, 'native Monster tables differ from frozen contract'
    else:
        OUTPUT.write_bytes(data)
    print(hashlib.sha256(data).hexdigest())
