"""Verify active installation and update only current Quadrant references; QA pending."""
from common import *
import csv,io,subprocess
from workspace_paths import get_path
game=get_path('bg2ee_game_root',required=True);gen=load(HERE/'current-generation.json');prod=load(HERE/'production.json');verification=load(HERE/'verification.json');receipt=load(HERE/'ingame-installation/active-test.json');baseline=load(HERE/'baseline.json')
assert receipt['status']=='installed-pending-ingame-qa'
assert file_sha(game/'iee-assets/creature-sprites/CreatureSprites-XN.catalog')==gen['catalog']['sha256']
for r in baseline['preserved']:assert file_sha(game/r['relative_path']).lower()==r['sha256'].lower()
for s in receipt['new_shards']:assert file_sha(game/s['registry']).upper()==s['sha256']
p=subprocess.run([str(PARENT/'composite_probe.exe'),str(game/'iee-assets/creature-sprites'),str(HERE/'work/composite.oracle')],capture_output=True,text=True,encoding='utf-8');(HERE/'native-installed.log').write_text(p.stdout+p.stderr);assert p.returncode==0,(p.stdout[-1000:],p.stderr)
native=json.loads(next(s for s in reversed(p.stdout.splitlines()) if s.startswith('{')));assert native==verification['native_composite']
write_json(HERE/'installed-native-verification.json',dict(passed=True,native_composite=native,catalog_sha256=gen['catalog']['sha256'],dll_sha256=gen['dll']['sha256'],DLL_unchanged=True,preserved_files=len(baseline['preserved']),frames=12928,resources=132,changed_outside_band=0,ingame_QA=False,release=False))
reference=relative(HERE/'current-generation.json');snapshot=relative(HERE/'installation-verification.json');receiptref=relative(HERE/'ingame-installation/active-test.json')
p=ROOT/'sprite/index/q3m-work-tracking.json';track=load(p);totals=dict(track['queue_totals']);family=next(f for f in track['families'] if f['engine_section']=='monster_quadrant')
previous=dict(family['current_full_production']);current=dict(previous,reference=reference,selection=relative(HERE/'selection.json'),installation_reference=receiptref,installation_snapshot=snapshot,seam_repair_reference=relative(HERE/'recipe.json'),parent_production_reference=previous['reference'],seam_changed_encoded_pixels=verification['changed_encoded_pixels'],seam_changed_outside_band=0,seam_contexts=3144,seam_new_neural_targets=prod['stats']['new_neural_targets'],scope=previous['scope']+'; contextual seam repair in four-native-pixel bands',state='family-complete-available-seam-corrected-installed-ingame-QA-pending')
family['current_full_production']=current;family['state']=current['state'];family['current_installation']=dict(family['current_installation'],reference=snapshot,receipt=receiptref,catalogue_sha256=gen['catalog']['sha256'],dll_sha256=gen['dll']['sha256'],qa_ingame=False)
family['current_colour_witness'].update(installation_reference=snapshot,state='installed-via-seam-corrected-complete-family-ingame-pending')
entry=next(e for e in track['current_recipe_complete_productions'] if e['family']=='monster_quadrant');entry.update(current)
track['engine_integration'].update(installed_candidate_reference=reference,latest_installation_verification_reference=snapshot)
assert track['queue_totals']==totals and totals['current_recipe_complete_animation_ids']==80 and totals['current_recipe_ingame_accepted_animation_ids']==72
write_json(p,track)
p=ROOT/'sprite/index/q3m-work-items.csv';raw=p.read_bytes();lines=raw.decode('utf-8-sig').splitlines(keepends=True);fields=next(csv.reader([lines[0]]));out=[lines[0]];changed=[]
for line in lines[1:]:
    row=dict(zip(fields,next(csv.reader([line]))))
    if row['animation_id'] not in gen['animation_ids']:out.append(line);continue
    row.update(queue_state='q3m-v7-full-seam-corrected-installed-ingame-pending',colour_variant_state='v7-contextual-seam-corrected-no-SDF-x2-installed-ingame-pending',q3m_v7_full_production_reference=reference,q3m_v7_installation_reference=receiptref)
    text=io.StringIO(newline='');csv.DictWriter(text,fields,lineterminator='\r\n' if line.endswith('\r\n') else '\n').writerow(row);out.append(text.getvalue());changed.append(row['animation_id'])
assert len(changed)==7;p.write_bytes((b'\xef\xbb\xbf' if raw.startswith(b'\xef\xbb\xbf') else b'')+''.join(out).encode())
p=ROOT/'sprite/SUIVI_Q3M.md';t=p.read_text(encoding='utf-8');t+='\n## Monster_quadrant : raccords contextuels installés — 2026-10-04\n\n- Sept palettes/132 feuilles/12 928 frames Q3m V7 x2 amélioré sans SDF ; reconstruction native des quatre parties sous K6 avant inférence, réparation limitée aux bandes4px natifs ;'+str(verification['changed_encoded_pixels'])+' pixels I/F modifiés, **zéro hors bande**, masques/classes/centres/cycles/palettes inchangés.\n- 3 144 contextes dédupliqués ;'+str(prod['stats']['new_neural_targets'])+' nouvelles cibles ;encodeur ROI uniquement. **272 frames non référencées** conservées (rectifie l\'estimation352 du rapport de prototype) ;65 déclarations0×0 inchangées.\n- DLL/shaders/INI/sept CLUA acquis inchangés ;6753 autres composants +55515 routes inchangés. [Run/CLUA](../'+relative(HERE/'README.md')+'). Catalogue actif161IDs/6885ressources/1705675frames. **Validation ingame en attente**, compteurs dix familles/80IDs installés et huit familles/72IDs acceptés inchangés.\n';p.write_text(t,encoding='utf-8')
p=ROOT/'sprite/index/README.md';t=p.read_text(encoding='utf-8');t+='\n- Monster_quadrant : [raccords contextuels Q3m installés, QA en attente](../../'+relative(HERE/'README.md')+'), sept palettes ;bandes4px natifs, aucune modification hors bandes, DLL/CLUA acquis conservés.\n';p.write_text(t,encoding='utf-8')
(HERE/'README.md').write_text('# Monster_quadrant — correction complète des raccords installée\n\n- **Installé, QA ingame en attente**. IDs1000/1003/1004/1100/1102/1103/1104, Q3m V7 K6 x2 palette améliorée, sans SDF ;132 feuilles/12 928 frames/36 BAM natifs.\n- Quatre parties assemblées sous K6 avant remplissage RGB/inférence, puis redécoupées ;feather uniquement sur4px natifs autour des frontières partagées. Encodeur limité à ROI ;I/F strictement inchangés hors bande, profils/palettes/guides/classes/centres/cycles/représentants inchangés.\n- 3 144 contextes, '+str(prod['stats']['new_neural_targets'])+' nouvelles cibles batch6 fp16 ;'+str(verification['changed_encoded_pixels'])+' pixels encodés modifiés, zéro hors bande. 272 frames non référencées +65 déclarations0×0 préservées. Chiffre272 rectifie352 du prototype, sans modifier son historique.\n- Catalogue :132 composants Quadrant remplacés ;6753 autres composants/161 memberships/55515 routes conservés ;actif6885 ressources/1 705 675frames. DLL/shaders/INI/fixtures CLUA acquis inchangés. Aucun traitement des33 BAM hors constructeur ni des MWDR1101/1105 absents.\n- Vérification12 928 frames K6×3formats isolé/combiné, 71 072 slots natifs ;'+str(native['native_composites'])+' assemblages natifs/'+str(verification['assembly_cases_with_empty_parts'])+' cas partiellement vides ;'+str(len(baseline['preserved']))+' fichiers acquis SHA préservés.\n- Autorités :`recipe.json`, `production.json`, `verification.json`, `current-generation.json`, `catalog-proof.json`, `ingame-installation/active-test.json`, `installation-verification.json`, `installed-native-verification.json`. `CLUA.txt` inchangé ;`comparison.png`, `seam-closeup.png` avant/après issus des feuilles finales, simulation CatmullRom per-cell sans contour/éclairage/occlusion ingame.\n- Sauvegarde catalogue `work/before`;restauration `restore.ps1` jeu/InfinityLoader fermés. Dix familles/80IDs installés, huit familles/72IDs acceptés inchangés ;aucune QA/release/commit déduite.\n',encoding='utf-8')
print(json.dumps(dict(installed=True,animation_ids=changed,changed_pixels=verification['changed_encoded_pixels'],outside_band=0,DLL_unchanged=True,accepted_ids=72)),flush=True)
