"""Generate the route2-only weather adapter from fpSEAM. Plan-only by default."""
from __future__ import annotations

import argparse
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / 'assets/override/fpTone.glsl'


def render_shader():
    source = (ROOT / 'assets/override/fpSEAM.glsl').read_text(encoding='utf-8')
    start = source.index('bool isBorderColor(')
    end = source.index('// Registry-described authored overlay timeline.', start)
    # fpTone uses a single native fetch, not fpSEAM's border interpolation.
    source = source[:start] + '''// Keep the native fpTone sampler for both the fallback and atlas phases.
vec4 seamSample(vec2 tc)
{
    return texture2D(uTex, tc);
}

''' + source[end:]
    source = source.replace('varying highp\tvec2\t\tvRef;\n', '')
    source = source.replace('// fpSEAM.glsl', '// fpTone.glsl — generated by tools/build_water_tone_shader.py')
    source = source.replace('// uIeeEnabled < 0.5 reproduces the vanilla fpSEAM output exactly.',
                            '// Unapproved draws and effect OFF reproduce native fpTone exactly.')
    marker = 'void main()\n{\n'
    if source.count(marker) != 1:
        raise ValueError('expected one shader entry point')
    fallback = '''    // Route2-only adapter: no legacy cell-wide replacement on weather draws.
    // Non-water, unknown identities and q=0 retain native sampling/tone/alpha.
    if (uIeeWaterRoute2 < 0.5 || uIeeEnabled < 0.5 || uIeeEnabled > 1.5 ||
        uIeeWaterOverlayStrength <= 0.0)
    {
        lowp vec4 c = texture2D(uTex, vTc) * vColor;
        lowp float grey = dot(c.rgb, vec3(0.299,0.587,0.114));
        lowp vec3 tone = grey * uColorTone.rgb;
        gl_FragColor = vec4(mix(c.rgb, tone, uColorTone.a), c.a);
        return;
    }
'''
    return source.replace(marker, marker + fallback)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--run', action='store_true')
    args = parser.parse_args()
    rendered = render_shader()
    changed = not OUTPUT.exists() or OUTPUT.read_text(encoding='utf-8') != rendered
    print(f'fpTone changed={changed}; action={"write" if args.run else "plan-only"}')
    if args.run and changed:
        OUTPUT.write_text(rendered, encoding='utf-8', newline='\n')


if __name__ == '__main__':
    main()
